#项目名称
module: "github.com/vuecmf/vuecmf-go" #项目名称，与go.mod中module保持一致

#当前运行环境
env: "dev"  #当前运行环境， dev 开发环境，test 测试环境，prod 生产环境

#是否开启调试模式
debug: true

#服务运行的端口
server_port: "8080"

#是否允许跨域请求
cross_domain:
  enable: true  #是否开启跨域请求
  allowed_origin: "http://localhost:8080, http://localhost:8081, http://localhost:8082"  #允许请求的来源，多个用英文逗号分隔，* 表示允许所有来源； 例如 http://www.vuecmf.com


#上传配置
upload:
  allow_file_size: 5        #允许上传的最大文件，单位M
  allow_file_type: "gif,jpg,jpeg,png,bmp,tif,txt,csv,xls,xlsx,doc,docx,zip,rar,gz,vsd,mdb,pdf,rmvb,flv,mp4,mp3,mpg,wmv,wav,avi,mid,ini,wps,mov,dbx,pst,ram"       #支持上传除图片外的文件类型
  allow_file_mime: "image/gif,image/jpeg,image/png,application/zip,application/octet-stream,text/plain; charset=utf-8,application/pdf"
  dir: "uploads"            #文件保存目录
  url: "http://localhost:8080/"  #文件访问链接域名
  image:
    resize_enable: true #是否缩放图片
    image_width: 600   #上传的图片裁切后的宽度
    image_height: 600  #上传的图片裁切后的高度
    keep_ratio: true #是否保持等比例缩放
    fill_background: 255 #填充的背景颜色 0 - 255 （R、G、B）的值共一个数值， 0 = 透明背景， 255 = 白色背景
    center_align: true #是否以图片的中心来进行等比缩放
    crop: true #是否裁切图片

#水印配置
water:
  enable: false
  water_font: "config/simhei.ttf"   #水印字体文件
  conf:
    size: 72.0 #水印文字大小
    message: "vuecmf" #水印文本内容
    position: 4  #水印位置， 0=左上角， 1=右上角，2=左下角，3=右下角，4=中间
    dx: 0  #文字x轴留白距离
    dy: 0  #文字y轴留白距离
    r: 0   #文字颜色值RGBA中的R值 0 - 255
    g: 0   #文字颜色值RGBA中的G值 0 - 255
    b: 0   #文字颜色值RGBA中的B值 0 - 255
    a: 50  #文字颜色值RGBA中的A值，即透明度 0 - 100

