default:
  type: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  database: photo
  charset: utf8
  prefix: vuecmf_
  debug: true

vuecmf:
  type: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  database: vuecmf
  charset: utf8
  prefix: vuecmf_
  debug: true