connect:
  default:
    type: mysql       #数据库类型
    host: 127.0.0.1   #数据库地址
    port: 3306        #端口
    user: root        #用户名
    password: 123456  #密码
    database: photo   #数据库名称
    charset: utf8     #字符编码
    prefix: vuecmf_   #表前缀
    max_idle_conn_nums: 10  #设置空闲连接池中连接的最大数量
    max_open_conn_nums: 100 #设置打开数据库连接的最大数量
    conn_max_lifetime: 2  #设置了连接可复用的最大时间，单位：分钟
    debug: true   #是否开启调试模式，开启后，控制台会打印所执行的SQL语句

  demo:
    type: mysql
    host: 127.0.0.1
    port: 3306
    user: root
    password: 123456
    database: demo
    charset: utf8
    prefix: vuecmf_
    max_idle_conn_nums: 10
    max_open_conn_nums: 100
    conn_max_lifetime: 60
    debug: true

  vuecmf:
    type: mysql
    host: 127.0.0.1
    port: 3306
    user: root
    password: 123456
    database: vuecmf
    charset: utf8
    prefix: vuecmf_
    max_idle_conn_nums: 10
    max_open_conn_nums: 100
    conn_max_lifetime: 60
    debug: true