connect:
  #开发环境
  dev:
    type: mysql       #数据库类型
    host: 127.0.0.1   #数据库地址
    port: 3306        #端口
    user: root        #用户名
    password: 123456  #密码
    database: demo   #数据库名称
    charset: utf8     #字符编码
    prefix: vuecmf_   #表前缀
    max_idle_conn_nums: 10  #设置空闲连接池中连接的最大数量
    max_open_conn_nums: 100 #设置打开数据库连接的最大数量
    conn_max_lifetime: 2  #设置了连接可复用的最大时间，单位：分钟
    skip_default_transaction: true #是否禁用默认事务, 若禁用默认事务 只在需要时使用事务 性能会提升30%+
    debug: true   #是否开启调试模式，开启后，控制台会打印所执行的SQL语句

  #测试环境
  test:
    type: mysql
    host: 127.0.0.1
    port: 3306
    user: root
    password: 123456
    database: demo
    charset: utf8
    prefix: vuecmf_
    max_idle_conn_nums: 10
    max_open_conn_nums: 100
    conn_max_lifetime: 60
    skip_default_transaction: true
    debug: true

  #生产环境
  prod:
    type: mysql
    host: 127.0.0.1
    port: 3306
    user: root
    password: 123456
    database: vuecmf
    charset: utf8
    prefix: vuecmf_
    max_idle_conn_nums: 10
    max_open_conn_nums: 100
    conn_max_lifetime: 60
    skip_default_transaction: true
    debug: false